version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - n8n_data:/home/node/.n8n
    restart: always

  spring-app:
    build: ./autoDemo
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - n8n

volumes:
  n8n_data:
